### ISSUE TITLE
What is wrong with this game????

### ISSUE THREAD

**Issue by khan-abd** [CodeWithSwastik/clash-of-chem#50]
- Issues with substrates not generating results/looping through the same reagents:
1. Benzoic acid
2. Propanenitrile
3. 1-Butene
4. Toluene
5. Benzaldehyde
6. Acetone

- Not able to select reagents occasionally
- Timer stops at times and game stops

**Comment by CodeWithSwastik** [comment]
I *think* I have fixed this with the recent commit.
